version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "Users"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"